/** UI 한글 문자열 */

export const S = {
  appTitle: "타입 상성 연습",
  setupHeading: "설정",
  defenderMode: "상대 타입 (공격 문제)",
  defenderSingle: "단일 타입만",
  defenderDual: "복수 타입 허용",
  practiceMode: "연습 범위",
  modeAttack: "공격만",
  modeDefense: "방어만",
  modeBoth: "둘 다 (문제마다 랜덤)",
  questionCount: "문제 개수 (N)",
  nHint: `1~500 사이 숫자`,
  start: "연습 시작",
  nInvalid: "문제 개수는 1 이상 500 이하로 입력해 주세요.",
  copyrightNote:
    "타입 이름·상성은 게임 규칙에 기반한 연습용입니다.",

  progress: (cur, total) => `${cur} / ${total} 문제`,
  problemAttack: "공격 문제",
  problemDefense: "방어 문제",
  opponentTypes: "상대 포켓몬 타입",
  targetMultiplier: "목표 배수",
  incomingMove: "들어오는 기술 타입",
  pickAttackType: "목표 배수를 만드는 공격 타입을 전부 고르세요.",
  pickDefenseTypes: "방어 타입을 하나 또는 두 개(서로 다름) 고르세요.",
  slot1: "타입 1",
  slot2: "타입 2",
  clearSlots: "초기화",
  attackBtn: "공격",
  defenseBtn: "방어",
  next: "다음 문제",
  yourMultiplier: "내 선택 배율",
  yourAttackChoices: "내가 고른 공격 타입",
  breakdown: "타입별 기여",
  optimalAttackTitle: "목표 배수 정답 타입 (전부)",
  optimalDefenseTitle: "가장 유리한 방어 조합 (전부)",
  alreadyOptimal: "정답을 모두 정확히 골랐습니다.",
  betterExistsAttack: "정답 타입 목록은 아래와 같습니다.",
  betterExistsDefense: "더 유리한 방어 조합(동률 최적 전부)은 아래와 같습니다.",
  sessionDone: "세션 종료",
  summaryHeading: "요약",
  summaryAttack: (hit, total) => `공격 문제: 정답 선택 ${hit} / ${total}`,
  summaryDefense: (hit, total) => `방어 문제: 최선 선택 ${hit} / ${total}`,
  again: "다시 설정하기",
};
